# Some of the settings were taken from the “How can I improve the
# running speed in DOSBox-X?” from this FAQ:
# <https://dosbox-x.com/wiki/#Home#_frequently_asked_questions_faq>.

[sdl]
priority = highest,highest
# This allows us to run DOSBox-X without X or Wayland.
videodriver = dummy

[dosbox]
machine = pc98
fastbioslogo = true
disable graphical splash = true
startbanner = false

[cpu]
core = dynamic
cycles = max

[render]
doublescan = false

[dos]
hard drive data rate limit = 0
floppy drive data rate limit = 0

[mixer]
nosound = true

[midi]
mididevice = none

[sblaster]
sbtype = none

[speaker]
pcspeaker = false

[autoexec]
MOUNT C Drives/C
CALL C:\INSTALL.BAT
ECHO Finished running C:\INSTALL.BAT.
