# SPDX-License-Identifier: LicenseRef-MIT-Nixpkgs
# SPDX-FileCopyrightText: 2003-2023 Eelco Dolstra and theNixpkgs/NixOS contributors
# SPDX-FileCopyrightText: 2024 Jason Yundt <jason@jasonyundt.email>
#
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
		{ device = "UUID=b5aafee4-daa4-495c-863f-f5823735a308";
			fsType = "bcachefs";
		};

	fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/52D3-0277";
			fsType = "vfat";
			options = [ "fmask=0022" "dmask=0022" ];
		};

	swapDevices =
		[ { device = "/dev/disk/by-uuid/e17575bf-fa97-455c-9831-46e171b5ae53"; }
		];

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.docker0.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp9s0.useDHCP = lib.mkDefault true;
	# networking.interfaces.virbr0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
